"""
Smart PDF Chatbot
------------------
A from-scratch redesign: PDFs are parsed page-by-page, split into
sentence-aware overlapping chunks, and indexed with BM25 (a proper
ranking function for keyword retrieval, not just raw TF-IDF cosine).
Scores are normalized to 0-1 so the relevance slider is meaningful.
If an Anthropic API key is supplied, retrieved passages are handed to
Claude for a short, precise, cited answer; otherwise the top passages
are shown directly.
"""

import re
import numpy as np
import streamlit as st
from pypdf import PdfReader

# =========================================================
# PAGE CONFIG + THEME (sky blue & white, black text)
# =========================================================
st.set_page_config(page_title="Smart PDF Chatbot", page_icon="📄", layout="wide")

st.markdown(
    """
    <style>
    :root {
        --blue: #0ea5e9;
        --blue-light: #e0f2fe;
        --blue-mid: #7dd3fc;
        --blue-dark: #0369a1;
    }
    .stApp { background: linear-gradient(180deg, #f0f9ff 0%, #ffffff 40%); color: #000000; }
    .stApp p, .stApp li, .stApp span, .stMarkdown, h1, h2, h3, h4 { color: #000000 !important; }

    section[data-testid="stSidebar"] {
        background-color: #ffffff;
        border-right: 2px solid var(--blue);
    }
    section[data-testid="stSidebar"] * { color: #000000 !important; }
    section[data-testid="stSidebar"] h2 { color: var(--blue-dark) !important; }
    section[data-testid="stSidebar"] input,
    section[data-testid="stSidebar"] .stSelectbox div[data-baseweb="select"] > div {
        background-color: #ffffff !important;
        border: 1px solid var(--blue) !important;
        border-radius: 8px;
    }

    .stButton > button, .stDownloadButton > button {
        background-color: #ffffff; color: #000000;
        border: 2px solid var(--blue); border-radius: 10px; font-weight: 600;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: var(--blue); color: #ffffff; border-color: var(--blue-dark);
    }

    div[data-testid="stChatMessage"] {
        background-color: #ffffff; border: 1px solid var(--blue-mid);
        border-radius: 14px; padding: 0.5rem 0.9rem; margin-bottom: 0.5rem;
        box-shadow: 0 1px 4px rgba(14,165,233,0.12);
    }

    section[data-testid="stFileUploaderDropzone"] {
        background-color: var(--blue-light); border: 2px dashed var(--blue); border-radius: 12px;
    }

    details { background-color: var(--blue-light); border-radius: 10px; border: 1px solid var(--blue-mid); }

    .confidence-badge {
        display: inline-block; padding: 2px 10px; border-radius: 999px;
        font-size: 0.75rem; font-weight: 700; color: #ffffff;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title("📄 Smart PDF Chatbot")
st.caption("Upload PDFs and ask questions. Retrieval uses BM25 ranking; "
           "answers are generated by Claude when an API key is supplied.")

# =========================================================
# SESSION STATE
# =========================================================
DEFAULTS = {
    "chunks": [],          # [{text, source, page}]
    "bm25": None,
    "tokenized_corpus": None,
    "processed_files": [],
    "chat": [],             # [{question, answer, passages}]
}
for key, val in DEFAULTS.items():
    if key not in st.session_state:
        st.session_state[key] = val

# =========================================================
# SIDEBAR
# =========================================================
with st.sidebar:
    st.header("⚙️ Settings")

    api_key = st.text_input(
        "Anthropic API key (optional)", type="password",
        help="Provide a key for a short, generated, cited answer. "
             "Without one, the top matching passages are shown directly.",
    )
    model_name = st.selectbox(
        "Model",
        ["claude-sonnet-4-6", "claude-opus-4-8", "claude-haiku-4-5-20251001"],
        disabled=not api_key,
    )

    st.divider()
    st.subheader("Retrieval")
    chunk_chars = st.slider("Chunk size (characters)", 300, 1200, 550, 50)
    overlap_chars = st.slider("Chunk overlap (characters)", 0, 300, 120, 20)
    top_k = st.slider("Passages to use", 1, 10, 5)
    min_confidence = st.slider(
        "Minimum confidence", 0.0, 1.0, 0.35, 0.05,
        help="Normalized 0-1 relevance score. Passages below this are ignored.",
    )

    st.divider()
    if st.button("🗑️ Clear session", use_container_width=True):
        for key, val in DEFAULTS.items():
            st.session_state[key] = val if not isinstance(val, list) else []
        st.rerun()

# =========================================================
# PDF PARSING
# =========================================================
def parse_pdf(file):
    """Return list of (page_number, cleaned_text)."""
    reader = PdfReader(file)
    pages = []
    for i, page in enumerate(reader.pages, start=1):
        text = page.extract_text() or ""
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n{2,}", "\n", text).strip()
        if text:
            pages.append((i, text))
    return pages


SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9])")


def sentence_aware_chunks(text, source, page, size, overlap):
    """Split on sentence boundaries, then pack sentences into ~size-char
    chunks with overlap, so chunks don't cut mid-sentence."""
    sentences = [s.strip() for s in SENTENCE_SPLIT.split(text) if s.strip()]
    if not sentences:
        return []

    chunks, current, current_len = [], [], 0
    for sent in sentences:
        if current_len + len(sent) > size and current:
            chunks.append(" ".join(current))
            # carry the tail of the previous chunk forward for overlap
            tail, tail_len = [], 0
            for s in reversed(current):
                if tail_len >= overlap:
                    break
                tail.insert(0, s)
                tail_len += len(s)
            current, current_len = tail[:], tail_len
        current.append(sent)
        current_len += len(sent)
    if current:
        chunks.append(" ".join(current))

    return [{"text": c, "source": source, "page": page} for c in chunks if len(c) > 25]


def tokenize(text):
    return re.findall(r"[a-z0-9]+", text.lower())


class SimpleBM25:
    """A small, dependency-free BM25 (Okapi) implementation — avoids relying
    on an external package that may not get installed on some deploy
    targets. Only needs numpy, which Streamlit already depends on."""

    def __init__(self, tokenized_docs, k1=1.5, b=0.75):
        self.k1 = k1
        self.b = b
        self.docs = tokenized_docs
        self.doc_lens = np.array([len(d) for d in tokenized_docs], dtype=float)
        self.avgdl = self.doc_lens.mean() if len(tokenized_docs) else 0.0

        self.doc_freqs = []  # per-doc term counts
        df = {}  # document frequency per term
        for doc in tokenized_docs:
            counts = {}
            for term in doc:
                counts[term] = counts.get(term, 0) + 1
            self.doc_freqs.append(counts)
            for term in counts:
                df[term] = df.get(term, 0) + 1

        n_docs = len(tokenized_docs)
        self.idf = {
            term: np.log(1 + (n_docs - freq + 0.5) / (freq + 0.5))
            for term, freq in df.items()
        }

    def get_scores(self, query_tokens):
        scores = np.zeros(len(self.docs))
        for term in query_tokens:
            idf = self.idf.get(term)
            if idf is None:
                continue
            for i, counts in enumerate(self.doc_freqs):
                f = counts.get(term, 0)
                if f == 0:
                    continue
                denom = f + self.k1 * (1 - self.b + self.b * self.doc_lens[i] / (self.avgdl or 1))
                scores[i] += idf * (f * (self.k1 + 1)) / denom
        return scores


def build_bm25_index(chunks):
    tokenized = [tokenize(c["text"]) for c in chunks]
    return SimpleBM25(tokenized), tokenized


def normalize_scores(scores):
    """Squash raw BM25 scores into 0-1 via their max, so the confidence
    slider means roughly the same thing regardless of corpus size."""
    scores = np.array(scores, dtype=float)
    top = scores.max() if scores.size else 0.0
    if top <= 0:
        return np.zeros_like(scores)
    return np.clip(scores / top, 0, 1)


def retrieve(question, bm25, chunks, k, min_conf):
    raw_scores = bm25.get_scores(tokenize(question))
    conf = normalize_scores(raw_scores)

    order = np.argsort(conf)[::-1]
    pool = order[: max(k * 3, 15)]
    candidates = sorted(i for i in pool if conf[i] >= min_conf)

    # merge an immediately-following chunk from the same source/page group
    # into the passage when it's also a candidate, for continuous context
    used, merged = set(), []
    for idx in candidates:
        if idx in used:
            continue
        group = [idx]
        used.add(idx)
        nxt = idx + 1
        if nxt < len(chunks) and nxt in candidates and chunks[nxt]["source"] == chunks[idx]["source"]:
            group.append(nxt)
            used.add(nxt)
        merged.append({
            "text": " ".join(chunks[i]["text"] for i in group),
            "source": chunks[idx]["source"],
            "page": chunks[idx]["page"],
            "confidence": float(max(conf[i] for i in group)),
        })

    merged.sort(key=lambda p: p["confidence"], reverse=True)
    return merged[:k]


# =========================================================
# ANSWER GENERATION
# =========================================================
def ask_claude(question, passages, api_key, model):
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    context = "\n\n".join(
        f"[{i+1} | {p['source']} p.{p['page']}] {p['text']}" for i, p in enumerate(passages)
    )
    system_prompt = (
        "Answer using ONLY the passages given. Be precise and brief: short "
        "sentences or a tight bullet list, no filler, no restating the question. "
        "Cite passages inline like [1], [2]. If the passages don't answer the "
        "question, say so in one sentence."
    )
    msg = client.messages.create(
        model=model,
        max_tokens=400,
        system=system_prompt,
        messages=[{"role": "user", "content": f"Passages:\n\n{context}\n\nQuestion: {question}"}],
    )
    return "".join(b.text for b in msg.content if b.type == "text")


def show_passages_directly(passages):
    if not passages:
        return "No passage met the confidence threshold for this question."
    lines = ["**Top matching passages:**"]
    for i, p in enumerate(passages, start=1):
        snippet = p["text"].strip()
        if len(snippet) > 260:
            snippet = snippet[:260].rsplit(" ", 1)[0] + " …"
        lines.append(f"**[{i}] {p['source']} p.{p['page']}** ({p['confidence']*100:.0f}% match) — {snippet}")
    return "\n\n".join(lines)


def confidence_color(c):
    if c >= 0.7:
        return "#0ea5e9"
    if c >= 0.4:
        return "#38bdf8"
    return "#94a3b8"


# =========================================================
# FILE UPLOAD & INDEXING
# =========================================================
uploaded = st.file_uploader("Upload PDF(s)", type="pdf", accept_multiple_files=True)

if uploaded:
    new_files = [f for f in uploaded if f.name not in st.session_state.processed_files]
    if new_files:
        with st.spinner(f"Indexing {len(new_files)} file(s)..."):
            for f in new_files:
                pages = parse_pdf(f)
                if not pages:
                    st.warning(f"⚠️ No extractable text in **{f.name}** (likely a scanned PDF).")
                    continue
                for page_num, text in pages:
                    st.session_state.chunks.extend(
                        sentence_aware_chunks(text, f.name, page_num, chunk_chars, overlap_chars)
                    )
                st.session_state.processed_files.append(f.name)

            if st.session_state.chunks:
                st.session_state.bm25, st.session_state.tokenized_corpus = build_bm25_index(
                    st.session_state.chunks
                )

    if st.session_state.processed_files:
        st.success(
            f"✅ {len(st.session_state.processed_files)} file(s) indexed "
            f"({len(st.session_state.chunks)} chunks): {', '.join(st.session_state.processed_files)}"
        )

has_index = st.session_state.bm25 is not None and st.session_state.chunks

# =========================================================
# CHAT
# =========================================================
st.divider()

for turn in st.session_state.chat:
    with st.chat_message("user"):
        st.write(turn["question"])
    with st.chat_message("assistant"):
        st.markdown(turn["answer"])
        if turn["passages"]:
            with st.expander("📌 Sources"):
                for i, p in enumerate(turn["passages"], start=1):
                    color = confidence_color(p["confidence"])
                    st.markdown(
                        f"**[{i}] {p['source']} — p.{p['page']}** "
                        f"<span class='confidence-badge' style='background:{color}'>"
                        f"{p['confidence']*100:.0f}% match</span>",
                        unsafe_allow_html=True,
                    )
                    st.info(p["text"])

question = st.chat_input("Ask a question about your PDF(s)..." if has_index else "Upload a PDF to get started")

if question:
    if not has_index:
        st.warning("Please upload at least one PDF first.")
    else:
        with st.chat_message("user"):
            st.write(question)
        with st.chat_message("assistant"):
            with st.spinner("Retrieving relevant passages..."):
                passages = retrieve(question, st.session_state.bm25, st.session_state.chunks, top_k, min_confidence)

            if api_key:
                with st.spinner("Generating answer..."):
                    try:
                        answer = ask_claude(question, passages, api_key, model_name)
                    except Exception as e:
                        answer = f"⚠️ Couldn't reach the Anthropic API ({e}).\n\n" + show_passages_directly(passages)
            else:
                answer = show_passages_directly(passages)

            st.markdown(answer)
            if passages:
                with st.expander("📌 Sources"):
                    for i, p in enumerate(passages, start=1):
                        color = confidence_color(p["confidence"])
                        st.markdown(
                            f"**[{i}] {p['source']} — p.{p['page']}** "
                            f"<span class='confidence-badge' style='background:{color}'>"
                            f"{p['confidence']*100:.0f}% match</span>",
                            unsafe_allow_html=True,
                        )
                        st.info(p["text"])

        st.session_state.chat.append({"question": question, "answer": answer, "passages": passages})

# =========================================================
# TRANSCRIPT DOWNLOAD
# =========================================================
if st.session_state.chat:
    transcript = "\n\n".join(f"Q: {t['question']}\nA: {t['answer']}" for t in st.session_state.chat)
    st.sidebar.divider()
    st.sidebar.download_button(
        "⬇️ Download transcript", data=transcript, file_name="chat_transcript.txt",
        mime="text/plain", use_container_width=True,
    )
